louvre_billetterie:
    resource: "@LouvreBilletterieBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/billetterie
    requirements:
        _locale: en|fr
    
    
#secure:
#    path:     /secure
#    defaults: { _controller: AppBundle:Main:secure }
#    schemes:  [https]