louvre_billetterie:
    resource: "@LouvreBilletterieBundle/Resources/config/routing.yml"
    prefix:   /billetterie
    
    
#secure:
#    path:     /secure
#    defaults: { _controller: AppBundle:Main:secure }
#    schemes:  [https]