louvre_billetterie_commande:
    path:     /
    defaults: { _controller: LouvreBilletterieBundle:Booking:commande }

louvre_billetterie_details:
    path:     /details
    defaults: { _controller: LouvreBilletterieBundle:Booking:details }
    
louvre_billetterie_payment:
    path:     /payment
    defaults: { _controller: LouvreBilletterieBundle:Booking:payment }
    
louvre_billetterie_confirmation:
    path:     /confirmation
    defaults: { _controller: LouvreBilletterieBundle:Booking:confirmation }
    
louvre_billetterie_tarifs:
    path:     /tarifs
    defaults: { _controller: LouvreBilletterieBundle:Booking:tarifs }
    
louvre_billetterie_mentions:
    path:     /mentions
    defaults: { _controller: LouvreBilletterieBundle:Booking:mentions }

louvre_billetterie_cgv:
    path:     /cgv
    defaults: { _controller: LouvreBilletterieBundle:Booking:cgv }
    